"""LangGraph state schema — the single source of truth for the agent loop."""

from typing import TypedDict, Annotated, Literal
from operator import add


class BugEntry(TypedDict):
    line: int
    type: str  # logic | off_by_one | edge_case | type | null_pointer
    description: str
    original: str
    sabotaged: str


class ExecResult(TypedDict):
    stdout: str
    stderr: str
    exit_code: int
    duration_ms: int
    sandbox: str  # "docker" | "fallback"


class RoundScore(TypedDict):
    write_score: int       # 0-40: original code correctness
    fix_score: int         # 0-60: debugging + fix quality
    bugs_fixed: int
    bugs_total: int
    code_quality: float  # 0-1
    correctness: float   # 0-1
    speed_bonus: float
    total: int  # 0-100 (write_score + fix_score)


class RoundRecord(TypedDict):
    round_num: int
    challenge: str
    original_code: str
    buggy_code: str
    fix_code: str
    bug_manifest: list[BugEntry]
    test_cases: list[dict]   # generated by saboteur
    original_exec: ExecResult | None
    buggy_exec: ExecResult | None
    fix_exec: ExecResult | None
    write_score: int          # 0-40: original code test pass rate
    write_test_results: dict | None  # raw test results from write phase
    score: RoundScore | None
    difficulty_in: str  # easy | medium | hard
    difficulty_out: str


RoundPhase = Literal[
    "setup",
    "student_writing",     # waiting for student to write original code
    "host_present",
    "sabotage",
    "executing_original",
    "executing_buggy",
    "student_fixing",
    "executing_fix",
    "evaluating",
    "round_complete",
    "done",
]


class SessionState(TypedDict):
    session_id: str
    language: str  # python | javascript
    topic: str
    difficulty: str  # easy | medium | hard
    round_num: int
    max_rounds: int
    original_code_submitted: bool  # gates whether saboteur can proceed
    phase: RoundPhase

    # Current round
    current_round: RoundRecord

    # History — append-only
    rounds: Annotated[list[RoundRecord], add]

    # Chat (Host messages to student)
    chat: Annotated[list[dict], add]

    # Tool-call trace (drives the frontend TracePanel)
    trace: Annotated[list[dict], add]

    # Error state
    error: str | None

    # Challenge de-duplication
    used_challenges: list[str]
